name: SAM Deploy 

on:
  push:
      branches: [ main ]
      paths:
      - 'backend/**'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

# sam build 
      - name: sam build
        working-directory: ./backend
        run: sam build --use-container 

# Run Unit tests- Specify unit tests here 
     ## - name: Run tests
      ##  run: |
          ## pushd './backend/tests/'
          ## pip install awscli
          ## python -m pip install --upgrade pip
          ## pip install -r requirements.txt      
          ## python -m nose2 test_getTodos.lambda_handler test_addTodo.lambda_handler test_completeTodo.lambda_handler

# sam deploy
      - name: sam deploy
        working-directory: ./backend
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name todo-houessou-com --s3-bucket 'aws-sam-cli-managed-default-samclisourcebucket-1m8qnzobarz4q' --capabilities CAPABILITY_IAM --region 'us-east-1'